# Generated by Django 3.0.7 on 2020-06-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.CharField(max_length=35)),
                ('comm_share', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'commission',
            },
        ),
        migrations.CreateModel(
            name='SlabDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab', models.CharField(max_length=22)),
                ('slab_amount', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'slab_details',
            },
        ),
    ]
