# Generated by Django 3.0.7 on 2020-06-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='comm_share',
        ),
    ]
