# Generated by Django 3.0.7 on 2020-06-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0002_remove_commission_comm_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slab.Commission')),
                ('slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slab.SlabDetails')),
            ],
            options={
                'db_table': 'set_commission',
            },
        ),
    ]
