# Generated by Django 3.0.7 on 2020-06-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0004_setcommission_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(max_length=22)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'distributers',
            },
        ),
        migrations.CreateModel(
            name='MakeCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('distributer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slab.Distributers')),
                ('distributer_comm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributer_comm', to='slab.SetCommission')),
                ('marchent_comm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marchent_comm', to='slab.SetCommission')),
                ('slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slab.SlabDetails')),
                ('zrupee_comm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zrupee_comm', to='slab.SetCommission')),
            ],
            options={
                'db_table': 'make_commission',
            },
        ),
    ]
