# Generated by Django 3.0.7 on 2020-06-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0005_distributers_makecommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='makecommission',
            name='tr_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
