# Generated by Django 3.0.7 on 2020-06-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0008_auto_20200609_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='makecommission',
            name='cust_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='makecommission',
            name='gst',
            field=models.CharField(default='0', max_length=55),
        ),
        migrations.AddField(
            model_name='makecommission',
            name='tds',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='distributers',
            name='dist_id',
            field=models.IntegerField(default=72278),
        ),
        migrations.AlterField(
            model_name='makecommission',
            name='dist_id',
            field=models.IntegerField(default=22557, unique=True),
        ),
    ]
