# Generated by Django 3.0.7 on 2020-06-10 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0010_auto_20200610_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributers',
            name='dist_id',
            field=models.IntegerField(default=2604),
        ),
        migrations.AlterField(
            model_name='makecommission',
            name='dist_id',
            field=models.IntegerField(default=84588, unique=True),
        ),
        migrations.AlterField(
            model_name='makecommission',
            name='slab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='slab.SlabDetails'),
        ),
    ]
